"""Pure math module for Weight of Evidence (WOE) and Information Value (IV) calculations."""

from __future__ import annotations

import logging
from typing import Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Calculation Logic
# ---------------------------------------------------------------------------

def safe_div(numerator: np.ndarray, denominator: np.ndarray) -> np.ndarray:
    """Safely divide two arrays, returning 0 where the denominator is 0.

    Parameters
    ----------
    numerator : np.ndarray
        The dividend array.
    denominator : np.ndarray
        The divisor array.

    Returns
    -------
    np.ndarray
        Result of the division, with 0s where denominator was 0.
    """
    return np.divide(
        numerator,
        denominator,
        out=np.zeros_like(numerator, dtype=float),
        where=(denominator != 0),
    )


def compute_aggregate_stats(bin_ids: np.ndarray, y: np.ndarray) -> pd.DataFrame:
    """Calculate bin-level statistics including bad/good counts and percentages.

    Parameters
    ----------
    bin_ids : np.ndarray
        Array of bin IDs (codes) assigned to each observation.
    y : np.ndarray
        Binary target array (1 for bad, 0 for good).

    Returns
    -------
    pd.DataFrame
        DataFrame indexed by 'bin', containing counts, bads, goods, and percentages.
    """
    unique_bins, inverse = np.unique(bin_ids, return_inverse=True)
    counts = np.bincount(inverse)
    bads = np.bincount(inverse, weights=y)
    goods = counts - bads

    total_bads = bads.sum()
    total_goods = goods.sum()

    bad_pct = safe_div(bads, total_bads)
    good_pct = safe_div(goods, total_goods)

    return pd.DataFrame(
        {
            "bin": unique_bins,
            "count": counts,
            "bad": bads,
            "good": goods,
            "bad_pct": bad_pct,
            "good_pct": good_pct,
        }
    ).set_index("bin")


def calculate_woe_iv(
    stats: pd.DataFrame,
    eps: float = 1e-12
) -> tuple[pd.Series, pd.Series, float]:
    """Compute WOE and IV for each bin and total feature IV.

    Parameters
    ----------
    stats : pd.DataFrame
        Aggregate stats generated by `compute_aggregate_stats`.
    eps : float
        Small constant to avoid division by zero or log(0).

    Returns
    -------
    tuple[pd.Series, pd.Series, float]
        A tuple containing (WOE Series, IV per bin Series, total feature IV).
    """
    # Weight of Evidence: ln(Distribution Good / Distribution Bad)
    woe = np.log((stats["good_pct"] + eps) / (stats["bad_pct"] + eps))

    # Information Value per bin: (Dist Good - Dist Bad) * WOE
    iv_bin = (stats["good_pct"] - stats["bad_pct"]) * woe

    return woe, iv_bin, float(iv_bin.sum())


def check_monotonicity(woe: pd.Series) -> dict[str, Any]:
    """Check if the calculated WOE trend is strictly increasing or decreasing.

    Parameters
    ----------
    woe : pd.Series
        Ordered WOE values for a feature (sorted by bin ID).

    Returns
    -------
    dict[str, Any]
        Dictionary containing 'is_monotonic' (bool) and 'direction' (str).
    """
    if len(woe) < 2:
        return {"is_monotonic": True, "direction": "none"}

    # Calculate differences between adjacent WOE values to check trend
    diff = np.diff(woe.values)
    is_inc = np.all(diff >= 0)
    is_dec = np.all(diff <= 0)

    return {
        "is_monotonic": bool(is_inc or is_dec),
        "direction": "increasing" if is_inc else "decreasing" if is_dec else "none",
    }